name: 'Update Plugins'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
jobs:
  UpdatePlugins:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up node 16.x'
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: "./scripts/update-plugins/package-lock.json"
      - name: 'Install dependencies'
        run: npm ci
        working-directory: scripts
      - name: 'Run update plugins script'
        timeout-minutes: 10
        run: node update-site-status
        id: node
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        working-directory: scripts/update_plugins
